### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by UnknownNull** [NoteLand/PlotSquaredPM#13]
2023-07-22 [13:10:45.818] [Server thread/CRITICAL]: ErrorException: "Implicit conversion from float 16.3 to int loses precision" (EXCEPTION) in "plugins/PlotSquaredPM-master/src/MyPlot/MyPlot" at line 269
--- Stack trace ---
  #0 plugins/PlotSquaredPM-master/src/MyPlot/MyPlot(269): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 8192, string[58] Implicit conversion from float 16.3 to int loses precision, string[121] C:\Users\Administrator\Documents\MV - RL\2.survival - pm5 - cplot test\plugins\P, int 269)
  #1 plugins/PlotSquaredPM-master/src/MyPlot/MyPlot(292): MyPlot\MyPlot->getPlotByPosition(object pocketmine\entity\Location#62039)
  #2 plugins/PlotSquaredPM-master/src/MyPlot/EventListener(327): MyPlot\MyPlot->getPlotByRoadPosition(object pocketmine\entity\Location#62039)
  #3 plugins/PlotSquaredPM-master/src/MyPlot/EventListener(303): MyPlot\EventListener->onEventOnMove(object pocketmine\player\Player#168130, object pocketmine\event\player\PlayerMoveEvent#60842)
  #4 pmsrc/src/event/RegisteredListener(61): MyPlot\EventListener->onPlayerMove(object pocketmine\event\player\PlayerMoveEvent#60842)
  #5 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerMoveEvent#60842)

**Comment by Crasher508** [comment]
Sorry for the long waiting time, I was on vacation. Error is fixed in commit https://github.com/NoteLand/PlotSquaredPM/commit/22e07e45b0c72a5d5ca0a86be9e8e86a778a5dd8

**Comment by Crasher508** [comment]
Thanks for reporting this error

**Comment by UnknownNull** [comment]
It does not load previous data
