### ISSUE TITLE
Old Databases 

### ISSUE THREAD

**Issue by UnknownNull** [NoteLand/PlotSquaredPM#14]
Databases and previous information from the old and original plugin are not loaded in this plugin

**Comment by Crasher508** [comment]
(english version below)
Bitte senden Sie genauere Informationen. Leider kann nicht immer ein Support für niedrigere Versionen garantiert werden.

Please send a specific error message from the log, I need more informations please.

**Comment by UnknownNull** [comment]
There is no error in the log and the server does not crash, only the plugin data is reset and the previous information is not loaded.

**Comment by Crasher508** [comment]
That's untypical, I can load old MyPlot data without problems.  Important are data\worlds\"worldName".yml folder, plots.db and config.yml.

**Comment by UnknownNull** [comment]
[MyPlot.zip](https://github.com/NoteLand/PlotSquaredPM/files/12777001/MyPlot.zip)
Test this

**Comment by UnknownNull** [comment]
This is old data that cannot be loaded

**Comment by Crasher508** [comment]
I look up your data, you have the tables plotsV2 and merged_plotsV2. Please choose the "sqliteV2" Provider
