### ISSUE TITLE
Stevekopf mit /p rand ist ein Zombiekopf

### ISSUE THREAD

**Issue by MonoAdrian23** [NoteLand/PlotSquaredPM#4]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?
Nutze /p rand und wähle den Stevekopf.
Angezeigt wird ein Skelettkopf als Rand

### Steps to reproduce the issue
1. Nutze /p rand
2. Wähle Stevekopf
3. Du siehst nun einen Skelettkopf

### OS and versions
 P2PM Dev 28
* Plugin Version:
* PocketMine-MP: 4.0.3
* PHP: 8.x
* Game version: PE

### Other Plugins
 Multiworld, TheSpawn

- If you remove all other plugins, does the issue still occur? Yes/No (delete as appropriate)
- If the issue is **not** reproducible without other plugins:
  - Have you asked for help in the community discord before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section.

**Comment by Crasher508** [comment]
With our newest update, plotsquaredpm.yml is parsed by StringToItemParser, your issue is fixed now
