### ISSUE TITLE
Frage: Economy API

### ISSUE THREAD

**Issue by MonoAdrian23** [NoteLand/PlotSquaredPM#5]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

Kleine Frage, gibt es bereits ein unterstütztes Economy Plugin für diese Version?
Wenn ja, welche?

### Steps to reproduce the issue
1. ...
2. ...

### OS and versions

* Plugin Version:
* PocketMine-MP:
* PHP:
* Game version: PE/Win10 (delete as appropriate)

### Other Plugins

- If you remove all other plugins, does the issue still occur? Yes/No (delete as appropriate)
- If the issue is **not** reproducible without other plugins:
  - Have you asked for help in the community discord before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section.

**Comment by Crasher508** [comment]
Actually you have to update EconomyAPI by yourself
