### ISSUE TITLE
Cant use /p rand and /p wand with Custom Permission

### ISSUE THREAD

**Issue by PocketMiner92** [NoteLand/PlotSquaredPM#6]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. Change the Permission to another, for example myplot.wand.1
2. Use /op name
3. Now you can See, you have OP but you cant use the Border or Wall

### OS and versions

* Plugin Version: Dev 28
* PocketMine-MP: 4.0.3
* PHP: 8.0.13
* Game version: PE

### Other Plugins

- PurePerms
- PureChat
- Multiworld
- TheSpawn
- EconomyApi 

- If you remove all other plugins, does the issue still occur? Yes (delete as appropriate)
- If the issue is **not** reproducible without other plugins:
  - Have you asked for help in the community discord before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section.

**Comment by Crasher508** [comment]
Use perms
myplot.border.default, myplot.border.admin, myplot.border.op

or 

myplot.wall.default, myplot.wall.admin, myplot.wall.op

Otherwise you have to register the new perm in PermissionManager

**Comment by PocketMiner92** [comment]
Ahhhh i have seen this too late.
Thank you very much!
Another Question.
I merging planned?

**Comment by Crasher508** [comment]
Plot Merging is finish, but not released yet

**Comment by PocketMiner92** [comment]
Is there a way to get this?
