### ISSUE TITLE
Plots suddenly without owners

### ISSUE THREAD

**Issue by Giulizo** [NoteLand/PlotSquaredPM#7]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. Switch from another MyPlot plugin for API 4 to PlotSquared
2. Some plots suddenly no longer have an owner, while others do

### OS and versions

* Plugin Version: [Dev #29](https://poggit.pmmp.io/babs/1dfc8)
* PocketMine-MP: 4.0.9
* PHP: 8
* Game version: PE/Win10 (delete as appropriate)

### Other Plugins

- If you remove all other plugins, does the issue still occur? Yes/No (delete as appropriate)
- If the issue is **not** reproducible without other plugins:
  - Have you asked for help in the community discord before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section.

**Comment by Crasher508** [comment]
Which DataProvider do you have in use?

**Comment by Crasher508** [comment]
PlotSquaredPM doesn't support the new plotsV2 SQLite Table
