### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by Ju999** [NoteLand/PlotSquaredPM#8]
Link to crashdump: https://crash.pmmp.io/view/5906664

### Additional comments (optional)
Der Bug kam, als ich /p gemacht habe (sollte das Form öffnen. Habe FormAPI installiert, hilft aber nix)

**Comment by Crasher508** [comment]
Use phar from poggit! You need pmforms virion (https://github.com/dktapps-pm-pl/pmforms)
